# Generated by Django 5.2.3 on 2025-06-23 13:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=500)),
                ('is_processed', models.BooleanField(default=False)),
                ('is_skipped', models.BooleanField(default=False)),
                ('extraction_cost', models.DecimalField(decimal_places=4, default=0, max_digits=8)),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['filename'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('current_step', models.IntegerField(choices=[(0, 'Read Docs'), (1, 'Upload'), (2, 'Extract'), (3, 'Sort'), (4, 'Aggregate')], default=0)),
                ('receipt_zip_filename', models.CharField(blank=True, max_length=255)),
                ('payer', models.CharField(blank=True, choices=[('sebastian', 'Sebastian'), ('iva', 'Iva')], max_length=20)),
                ('current_extraction_index', models.IntegerField(default=0)),
                ('files_processed', models.IntegerField(default=0)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_sort_index', models.IntegerField(default=0)),
                ('api_costs_total', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('is_complete', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReceiptItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=500)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.extractedfile')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt_items', to='core.receiptsession')),
            ],
            options={
                'ordering': ['source_file__filename', 'id'],
            },
        ),
        migrations.AddField(
            model_name='extractedfile',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_files', to='core.receiptsession'),
        ),
        migrations.CreateModel(
            name='SessionAggregation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sebastian_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('iva_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('both_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grand_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transfer_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transfer_direction', models.CharField(blank=True, max_length=50)),
                ('calculated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aggregation', to='core.receiptsession')),
            ],
        ),
        migrations.CreateModel(
            name='SortedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignee', models.CharField(choices=[('sebastian', 'Sebastian'), ('iva', 'Iva'), ('both', 'Both')], max_length=20)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('receipt_item', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='sorted_assignment', to='core.receiptitem')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sorted_items', to='core.receiptsession')),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
    ]
